version: "3.0"
services:
  api:
    image: ghcr.io/adrianvillanueva997/blog-adrian-villanueva:latest
    networks:
      - proxy
    container_name: blog-adrian-villanueva.com
    restart: unless-stopped
    labels:
      - com.ouroboros.enable=true
      - "traefik.enable=true"
      - "traefik.http.middlewares.avm-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.middlewares.avm-redirect-websecure.redirectscheme.permanent=true"
      - "traefik.http.routers.avm-web.middlewares=avm-redirect-websecure"
      - traefik.http.routers.avm-web.rule=Host(`blog.adrian-villanueva.com`)
      - traefik.http.routers.avm-web.entrypoints=http
      - traefik.http.routers.avm-websecure.rule=Host(`blog.adrian-villanueva.com`)
      - traefik.http.routers.avm-websecure.tls.certresolver=le
      - traefik.http.routers.avm-websecure.tls=true
      - traefik.http.routers.avm-websecure.entrypoints=https
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
